Update hw/units/Makefile

diff --git a/hw/units/Makefile b/hw/units/Makefile
--- a/hw/units/Makefile
+++ b/hw/units/Makefile
@@ -15,8 +15,16 @@ units: $(addsuffix /rtl, ${IP_RTL_LIST})
 # Fetch sources for all IPs without local rtl
 custom_%/rtl:
 	cd ${HW_UNITS_ROOT}/custom_$*; source fetch_sources.sh \
-		&& echo "[UNITS] Sources succesfully fetched at $@" \
-		|| echo "[UNITS] Failed to fetch sources for $@" \; rm -rf $@
+# 	Check if sources are preset, error otherwise and clean stale dir
+	if [ -z "$(shell ls -A $${HW_UNITS_ROOT}/$$@)" ]; then \
+		echo "[UNITS] Failed to fetch sources for $@"  >&2; \
+		rm -rf $@; \
+		false; \
+	fi
+
+# Selectively remove a single RTL dir
+clean_custom_%:
+	rm -rf ${HW_UNITS_ROOT}/$*/rtl
 
 # Remove all RTL dirs
 clean:
